apiVersion: v1
kind: ConfigMap
metadata:
  name: sharded-mongodb
  namespace: mongodb-lab2
data:
  projectName: sharded-mongodb
  orgId: 5b890e0feacf0b76ff3e7183 # this is a required parameter
  baseUrl: https://ops.example.com:8443